# docker compose build
# docker compose up

services:
  application:
    build: .
    ports:
      - "5000:5000"

  database:
    image: basex/basexhttp:latest
    ports: # Example port mapping, can be used later to connect from application like: database:8000
      - "1984:5000"
    environment:
      - user=admin
      - password=hej123
      

volumes:
  db-data: