# docker compose build
# docker compose up

services:
  application:
    build: .
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    
    depends_on:
      - existdb

  existdb:
    image: existdb/existdb:release
    container_name: exist

    environment:
      - EXIST_DB_USER: "admin"
      - EXIST_DB_PASSWORD: "123"
    ports:
        - 8080:8080
        - 8443:8443
    networks:
      - mynetwork

volumes:
  data:
    driver: local
    name: exist-data
  config:
    driver: local
    name: exist-config



networks:
  mynetwork:
    name: mynetwork
    driver: bridge