# docker compose build
# docker compose up

services:
  application:
    build: .
    depends_on:
      - database
    

  database:
    image: basex/basexhttp:latest
    ports: # Example port mapping, can be used later to connect from application like: database:8000
      - "1984:1984"
  
      

volumes:
  db-data: