# docker compose build
# docker compose up

services:
  application:
    build: .
    ports:
      - "5000:5000"

  database:
    image: mysql:latest
    ports: # Example port mapping, can be used later to connect from application like: database:8000
      - "8000:8000"
    volumes: # For persisting data
      - db-data:/var/lib/mysql

volumes:
  db-data: