# docker compose build
# docker compose up

services:

#todo: fix erno 111
  application:
    build: ./
    depends_on:
      - database

    ports:
    - "5000:5000"
    restart: always 

  database:
    #
    image: basex/basexhttp:latest
    ports: 
      - "1984:1984"
    restart: always
      

volumes:
  db-data: